apiVersion: v1
kind: Secret
metadata:
  name: nutrigraph-secrets
  namespace: default
  labels:
    app.kubernetes.io/part-of: nutrigraph-ai
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  NEO4J_USER: "${NEO4J_USER}"
  NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
  NEO4J_AUTH: "${NEO4J_AUTH}"
